### ISSUE TITLE
Problem with last release 1.4.1 and Titanium SDK 3.5.0

### ISSUE THREAD

**Issue by ottopic** [appcelerator-modules/ti.airprint#4]
Hi,
I have updated my ti.airprint module, but now it doesn't work and it return that error:

Unsupported primitive return type: B for target:[object TiAirprintModule]->canPrint:

I don't understand the problem but my code with previous release works fine. Can someone help me?

Best regards

**Comment by muhammaddadu** [comment]
Hey @ottopic, please try the latest version 'ios-1.4.2'.

**Comment by ottopic** [comment]
@muhammaddadu I'm sorry but I have the same error with 1.4.2 too.

**Comment by ottopic** [comment]
Does anyone tried it? Does it works? I can not make it work....

**Comment by muhammaddadu** [comment]
Hey @ottopic, the issue seemed to be with the Titanium SDK. You can download the latest version from [here](http://builds.appcelerator.com/#3_5_X). This should resolve the issue with the module.

**Comment by muhammaddadu** [comment]
@ottopic, We have updated the module to v1.4.3. This should fix the issue before the next GA comes out.

**Comment by ottopic** [comment]
@muhammaddadu Thank you very much. I'll try soon! :)

**Comment by ottopic** [comment]
@muhammaddadu I can confirm that works fine! Great works.

Best regards
Lore
